### ISSUE TITLE
File manifest.json doesn't exist.

### ISSUE THREAD

**Issue by GaTechThomas** [getgauge-examples/gauge-taiko-docker-compose#5]
Do the examples really work? I've tried several options and keep getting error

`File manifest.json doesn't exist.`

This example file is one that is problematic:

https://github.com/getgauge-examples/template-docker-compose/blob/master/Dockerfile

**Comment by zabil** [comment]
An upto date version of the docker file is available at https://github.com/getgauge/template-js/blob/master/Dockerfile

This is available when initializing a project using `gauge init js`
